[package]
name = "test-dlpack-multi-languages"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
pyo3 = {version = "0.22", features = ["auto-initialize"]}
ndarray = "*"
dlpack = {path = "..", features = ["ndarray"]}

[build-dependencies]
pyo3-build-config = "0.22"
