[package]
name = "dlpk"
version = "0.3.1"
edition = "2024"
rust-version = "1.88"
license = "MIT OR Apache-2.0"

authors = [
    "Guillaume Fraux <guillaume.fraux@epfl.ch>",
    "Rohit Goswami <rohit.goswami@epfl.ch>",
]

description = "DLPack integration for Rust"

repository = "https://github.com/metatensor/dlpk"
readme = "README.md"
keywords = ["dlpack", "deep-learning", "machine-learning"]

[dependencies]
ndarray = { version = "0.17", optional = true }
pyo3 = { version = "0.29", optional = true }
ouroboros = { version = "0.18", optional = true }
half = { version = "2.7", optional = true }

[features]
ndarray = ["dep:ndarray"]
pyo3 = ["dep:pyo3"]
half = ["dep:half"]
sync = ["dep:ouroboros"]
